/**
 * Shared bits for the vario-sound article components (VarioPlayer, VarioZones,
 * VarioLineChart). The data under src/data/vario-sound/ is generated by the
 * configurator repo (scripts/article-vario-sound.ts) from the same model the
 * configurator's simulator runs.
 */

/** Configurator the article links into; staging builds point at the staging one. */
export const CONFIG_BASE: string = import.meta.env.PUBLIC_CONFIG_BASE ?? 'https://config.flybeeper.com'

export function configLink(fragment: string): string {
  return `${CONFIG_BASE}/settings/audio#preset=${fragment}`
}

/** m/s with sign, two decimals, typographic minus. */
export function ms(v: number): string {
  return `${v > 0 ? '+' : v < 0 ? '−' : ''}${Math.abs(v).toFixed(2)}`
}

export type ZoneKind = 'sink' | 'sink-memory' | 'quiet' | 'climb-memory' | 'early-exit' | 'climb'

export interface ZoneData { kind: ZoneKind, from: number | null, to: number | null }

/** Thresholds in cm/s, as the model keeps them. */
export interface ParamsData { climbOn: number, climbOff: number, sinkOn: number, sinkOff: number, hyst: number }

export const ZONE_LABEL: Record<ZoneKind, string> = {
  'sink': 'sink tone',
  'sink-memory': 'sink tone held',
  'quiet': 'silent',
  'climb-memory': 'climb tone held',
  'early-exit': 'early exit',
  'climb': 'climb tone',
}

/** Reference lines for a chart, labels pushed apart so they never overlap. */
export function refLines(p: ParamsData, lo: number, hi: number, y: (v: number) => number, minGap = 12) {
  const refs: { v: number, label: string, cls: string }[] = [
    { v: p.climbOn / 100, label: `C-ON ${ms(p.climbOn / 100)}`, cls: 'on' },
  ]
  if (p.hyst > 0)
    refs.push({ v: (p.climbOn + p.hyst) / 100, label: `+H ${ms((p.climbOn + p.hyst) / 100)}`, cls: 'early' })
  if (p.climbOff < p.climbOn)
    refs.push({ v: p.climbOff / 100, label: `C-OFF ${ms(p.climbOff / 100)}`, cls: 'off' })
  refs.push({ v: p.sinkOn / 100, label: `S-ON ${ms(p.sinkOn / 100)}`, cls: 'sink' })
  if (p.sinkOff > p.sinkOn)
    refs.push({ v: p.sinkOff / 100, label: `S-OFF ${ms(p.sinkOff / 100)}`, cls: 'sinkoff' })
  refs.push({ v: 0, label: '0', cls: 'zero' })
  const shown = refs
    .filter(r => r.v >= lo && r.v <= hi)
    // Equal values (a hold that collapses onto its ON line) keep the first.
    .filter((r, i, all) => all.findIndex(o => o.v === r.v) === i)
    .map(r => ({ ...r, y: y(r.v), ly: y(r.v) }))
    .sort((a, b) => a.y - b.y)
  for (let i = 1; i < shown.length; i++) {
    if (shown[i].ly - shown[i - 1].ly < minGap)
      shown[i].ly = shown[i - 1].ly + minGap
  }
  return shown
}
